In [1]:
import numpy as np

In [2]:
# 1)Create a 3×3 numpy array of all True’s
x = np.ones((3,3), dtype=bool)
x

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [3]:
# 2) Extract all odd numbers from arrays 
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]) 
arr[arr%2 == 1]

array([1, 3, 5, 7, 9])

In [4]:
# 3)Replace all even numbers in above array with -5 
arr[arr%2 == 0] = 5
print(arr)

[5 1 5 3 5 5 5 7 5 9]


In [5]:
# 4) Reshape an array 
x = np.array([ 0, 1, 2, 3, 4, 5, 6, 7, 8, 9]) 
x.reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [6]:
# 5)How to get the positions where elements of two arrays match 
a = np.array([1,2,3,2,3,4,3,4,5,6]) 
b = np.array([7,2,10,2,7,4,9,4,9,8]) 

print((a==b).all())
print(np.where(a==b))

False
(array([1, 3, 5, 7], dtype=int64),)


In [7]:
#6) Swap columns 1 and 2 in the array 
y = np.array ([[1,2,3],[4,5,6],[7,8,9]])
print("Original array:")
print(y)
y[:, [1,0]] = y[:, [0, 1]]
print("After swapping arrays the last column and first column:")
print(y)

Original array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
After swapping arrays the last column and first column:
[[2 1 3]
 [5 4 6]
 [8 7 9]]


In [8]:
# 7) Reversing the columns of a 2D array 
z = np.array([[1,2,3],[4,5,6],[7,8,9]])
print("Original array:")
print(z)
flip_array = np.flip(z[::-1])
print("After flipping array:")
print(flip_array)

Original array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
After flipping array:
[[3 2 1]
 [6 5 4]
 [9 8 7]]


In [9]:
# 8) Create a 2D array of shape 5x3 to contain random decimal numbers between 5 and 10 
d = np.random.uniform(low=5,high=10,size=(5,3))
d

array([[6.12322289, 8.27542313, 7.0119224 ],
       [8.93147301, 9.19544462, 7.618034  ],
       [8.72460201, 5.83310324, 5.31616388],
       [6.77249742, 7.83262018, 8.11205481],
       [6.33340611, 7.67129294, 7.48207663]])

In [10]:
# 9) Create a 2d array with 1 on the border and 0 inside in the array
arr = np.ones((10,10))
print("Original array:")
print(arr)
print("1 on the border and 0 inside in the array")
arr[1:-1,1:-1] = 0
print(arr)

Original array:
[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]
1 on the border and 0 inside in the array
[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [11]:
# 10) Write script to produce the desired output.
X = np.array([[9,1,12,3],[14,15,6,7], [18,9,10,11]]) 
row = np.array([0,1,2])
col = np.array([2,0,3])
print('row: ',row)
print('col: ',col)
X[row,col]

row:  [0 1 2]
col:  [2 0 3]


array([12, 14, 11])